# Generated by Django 2.2.4 on 2023-02-01 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientName', models.CharField(max_length=45, null=True)),
                ('sex', models.IntegerField()),
                ('doctorName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_id', to='medicalSystemApp.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='photoGalleray',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploadPic', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('createAt', models.DateField(auto_now_add=True, null=True)),
                ('patientPhotoGalleray', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients_PhotoGalleray', to='medicalSystemApp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='dentalNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=45, null=True)),
                ('createAt', models.DateField(auto_now_add=True, null=True)),
                ('patientDentalNotes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients_DentalNotes', to='medicalSystemApp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='billingHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('description', models.CharField(max_length=45, null=True)),
                ('createAt', models.DateField(auto_now_add=True, null=True)),
                ('patientBillingHistory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients_BillingHistory', to='medicalSystemApp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='basic_information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastName', models.CharField(max_length=45, null=True)),
                ('birthDate', models.DateField(null=True)),
                ('country', models.CharField(max_length=15, null=True)),
                ('address', models.CharField(max_length=25, null=True)),
                ('phone', models.IntegerField(null=True)),
                ('underTreatment', models.IntegerField(default=0, null=True)),
                ('treatment', models.CharField(max_length=25, null=True)),
                ('prescriptions', models.CharField(max_length=25, null=True)),
                ('alergies', models.CharField(max_length=25, null=True)),
                ('pregnant', models.IntegerField(default=0, null=True)),
                ('diseases', models.CharField(max_length=25, null=True)),
                ('patient_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients_info', to='medicalSystemApp.patient')),
            ],
        ),
    ]
