# Generated by Django 2.2.4 on 2023-02-04 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicalSystemApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MidNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=45, null=True)),
                ('createAt', models.DateField(auto_now_add=True, null=True)),
                ('patientMidNotes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients_MidNotes', to='medicalSystemApp.patient')),
            ],
        ),
        migrations.AddField(
            model_name='billinghistory',
            name='type',
            field=models.CharField(default='NULL', max_length=25, null=True),
        ),
        migrations.DeleteModel(
            name='dentalNotes',
        ),
    ]
