# Generated by Django 2.2.4 on 2023-02-04 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicalSystemApp', '0002_auto_20230204_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photogalleray',
            name='patientPhotoGalleray',
        ),
        migrations.AddField(
            model_name='photogalleray',
            name='patientmidPhoto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='patients_midPhoto', to='medicalSystemApp.patient'),
        ),
    ]
